### ISSUE TITLE
Add guidence in ReadMe as differneces (strengths/weaknesses) between GeoArrays.jl and Raster.jl

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/GeoArrays.jl#116]
I wonder if some verbiage should be added distinguishing GeoArrays.jl from Raster.jl. From what I can gather GeoArrays.jl is much lighter weight and less comprehensive? Does GeoArrays have a different mission statement? Similar text on Raster.jl would show a cohesive community.

**Comment by evetion** [comment]
Good suggestion, @rafaqz and I do work together a lot.

For me GeoArrays and Rasters are like Pythons rasterio and xarray. So one just for simple raster interaction, like a geotiff, the latter for multi dimensional raster stacks, netcdf etc.

We are figuring out a way in GeoInterface so that our structs are fully interchangeable.

**Comment by rafaqz** [comment]
Although Rasters.jl also has more of the rasterio functionality like rasterising polygons, zonsl stats etc. But that also works on xarray shaped data ;)

**Comment by evetion** [comment]
Now [documented](https://github.com/evetion/GeoArrays.jl#alternatives).
