### ISSUE TITLE
GeoArrays Plot example not producing the suggested output

### ISSUE THREAD

**Issue by luraess** [evetion/GeoArrays.jl#55]
I am currently investigating how to plot 2D heatmap as function of 2D x and y coordinate field within the `Plots.jl` framework ([see here](https://discourse.julialang.org/t/how-to-plot-a-2d-rotated-array/47603)) and came across your last example from the README. There, you plot a 2D map in apparently rotated coordinate. Trying to reproduce the code snippet
```julia
# Plot a GeoArray
julia> using Plots
julia> fn = download("https://github.com/yeesian/ArchGDALDatasets/blob/master/pyrasterio/RGB.byte.tif?raw=true")
julia> ga = GeoArrays.read(fn)
julia> plot(ga)

# or plot a band other than the first one
julia> plot(ga, band=2)
```
I could not manage to get the same output as depicted on the GeoArrays README. The figure I obtained was different (low-res) and not rotated.

**Comment by evetion** [comment]
Well, GeoArrays doesn't rotate it. This is just a projected raster that has a lot of missing data around the edges, therefore appearing to be rotated. Sorry to disappoint.

However, your plot should be the same as the README. Could you post a screenshot, mention your OS and GeoArrays version? This might be due to your default `Plots.jl` backend. This is my result on Fedora (note the jagged pixelated edge of the raster, indicating it's non-rotated):

![Screenshot from 2020-10-03 13-12-07](https://user-images.githubusercontent.com/8655030/94990132-5292f600-0569-11eb-8cc7-25189468a63c.png)

**Comment by luraess** [comment]
Apologies for having opened this issue. The code snipped produces now the desired output
![geoarray_out](https://user-images.githubusercontent.com/61313342/94993917-8a636300-0594-11eb-95a7-724f6227b3c5.png)
I tried it several times before filing the issue, with restarting Julia in-between. Have no clue why it did not work then. Anyway, good so.

Regarding the "rotation": rotating may be not the most appropriate word. I meant that I am looking a way to plot a 2D field (data) as function of 2D x and y coordinate fields (as in `pcolor()` from `PyPlot` [see here](https://discourse.julialang.org/t/how-to-plot-a-2d-rotated-array/47603)). As such, one could then pass x and y coordinate that are not aligned with the cartesian 2D axis. If you have any suggestions how to do this using `Plots.jl` I would be happy to know as It seems you do so to produce the example figure we are discussing now.

**Comment by dgatey-rms** [comment]
Does plot need to be exported or which plot backend are you using? 
For the above example I get an error that that there is no method matching Plots with a GeoArray.

**Comment by visr** [comment]
The plot backend should not matter, this package uses `RecipesBase` to tell Plots how  it should be plotted. Could it be that you have an old version of GeoArrays installed?

**Comment by dgatey-rms** [comment]
Seems to be a Windows vs Linux issue. On my Linux environment (Julia 1.4) it has the latest version, however in Windows (Julia 1.4 and 1.5) it only updates to 0.1.0 - will check the dependencies etc. and see if I can sort out why

**Comment by visr** [comment]
Hmm the package compatibilities are platform agnostic. Probably a package in your environment is holding it back from the latest version. Installing in an empty environment should work. Or you can try `pkg> add GeoArrays@0.3.3` to see what is the reason you are not getting the latest version.

**Comment by dgatey-rms** [comment]
Thanks, I was able to trace through a number of issues through GDAL, etc. the final culprit being a compatibility requirement of RecipesBase on JuliaDB.
![image](https://user-images.githubusercontent.com/30471444/102895948-893c2680-445d-11eb-917a-9ce8ef29c865.png)

FYI - regarding the issue flagged in the original post, I had initially experienced the same outcome but it was simply because the tif used in the `Read TIF file` example is different (lower quality and square as pointed out earlier) to the one used in the plot example.

**Comment by evetion** [comment]
Happy to hear that you figured out the underlying issue! 👍

**Comment by evetion** [comment]
Just note that we now support plotting rotated rasters as well. :tada:
